version: "3.8"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3000:3000"
      - "443:443"
    networks:
      - db_network
      - api_network
    volumes:
      - ./src:/var/www/html
      - /mnt:/var/www/html/srcWeb/storage/app/public

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"

    mem_limit: 1000000000
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - db_network

  wrapper:
    build:
      context: ./wrapper
      dockerfile: Dockerfile
    networks:
      - db_network
    volumes:
      - ./wrapper/var/:/var/
      - /mnt:/mnt

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - db_network
      - api_network
    volumes:
      - ./api/var/:/var/
      - /mnt:/mnt
    ports:
      - "8000:8000"

networks:
  db_network:
    driver: bridge
  api_network:
    driver: bridge
