#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication snappyHexMesh -overwrite

runApplication renumberMesh -overwrite

restore0Dir

runApplication $(getApplication)

#------------------------------------------------------------------------------

$(getApplication) -postProcess -func writeCellCentres -latestTime

touch temp.foam
