#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

#-------------------- Parallel Run Script ------------------

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication snappyHexMesh -overwrite

#runApplication renumberMesh -overwrite

restore0Dir

#------------------------------------------------------------------------------
runApplication decomposePar
#------------------------------------------------------------------------------

runParallel $(getApplication)

#------------------------------------------------------------------------------
#runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime
#------------------------------------------------------------------------------

postProcess -func writeCellCentres -latestTime

touch temp.foam
