#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

#-------------------- Parallel Run Script ------------------

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication snappyHexMesh -overwrite

runApplication topoSet

#runApplication renumberMesh -overwrite

restore0Dir

#------------------------------------------------------------------------------
runApplication decomposePar
#------------------------------------------------------------------------------

runParallel $(getApplication)

# Get status
status=$?

#------------------------------------------------------------------------------
#runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime
#------------------------------------------------------------------------------

# Remove processorDir when Normal End

if [ "$status" -eq 0 ]; then
  echo " End Status = $status "
  rm -r processor*
fi

postProcess -func writeCellCentres -latestTime

touch temp.foam
